### ISSUE TITLE
Not working on Blender 5.0.0

### ISSUE THREAD

**Issue by Macintosh-Fan** [james-gambino/snow-generator#1]
I attempted to install the script, but it did not work on my end for some reason: I cannot see the option to enable it in a world, or simply see it at all in the extensions menu.

**Comment by Macintosh-Fan** [comment]
Oh wait, the menu layout completely changed. I will reopen in case there are specific issues for Blender 5.0.0.

**Comment by Macintosh-Fan** [comment]
Nevermind, I got this error:
```
Python: Traceback (most recent call last):
  File "/Users/MY_USERNAME/Library/Application Support/Blender/5.0/scripts/addons/__snow_gen__.py", line 126, in execute
    apply_snow_modifiers(snow, decimate_ratio)
  File "/Users/MY_USERNAME/Library/Application Support/Blender/5.0/scripts/addons/__snow_gen__.py", line 161, in apply_snow_modifiers
    snow.cycles.use_adaptive_subdivision = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CyclesObjectSettings' object has no attribute 'use_adaptive_subdivision'
```
